/**
 * City → country base, ported from the prototype and re-canonicalised to
 * English (the product's v1 interface language).
 *
 * A plain string is a city whose English name is the only one we need. A tuple
 * is `[canonical, ...aliases]`: the aliases exist so someone typing "Berlim",
 * "Munique" or "München" still lands on Berlin and Munich. Aliases are matched
 * but never stored — the record keeps the canonical name, which is what makes
 * "response rate by country" comparable later.
 *
 * Kept local and in-memory on purpose: autocomplete must answer instantly and
 * must not depend on the network.
 */
export type CountryEntry = {
  name: string;
  aliases?: readonly string[];
  cities: ReadonlyArray<string | readonly [string, ...string[]]>;
};

export const COUNTRIES: readonly CountryEntry[] = [
  {
    name: "Germany",
    aliases: ["Alemanha", "Deutschland"],
    cities: [
      ["Berlin", "Berlim"],
      ["Munich", "Munique", "München"],
      ["Hamburg", "Hamburgo"],
      ["Cologne", "Colônia", "Köln"],
      ["Frankfurt", "Frankfurt am Main"],
      "Stuttgart",
      ["Düsseldorf", "Dusseldorf"],
      "Leipzig",
      "Dresden",
      ["Hanover", "Hanôver", "Hannover"],
      ["Nuremberg", "Nürnberg"],
      "Karlsruhe",
      "Bremen",
      "Essen",
      "Dortmund",
      "Freiburg",
      "Heidelberg",
      ["Münster", "Munster"],
      "Aachen",
      "Potsdam",
    ],
  },
  {
    name: "Portugal",
    cities: [
      ["Lisbon", "Lisboa"],
      ["Porto", "Oporto"],
      "Braga",
      "Coimbra",
      "Aveiro",
      "Faro",
      "Funchal",
      ["Guimarães", "Guimaraes"],
      "Leiria",
      ["Setúbal", "Setubal"],
      ["Évora", "Evora"],
      "Viseu",
    ],
  },
  {
    name: "Spain",
    aliases: ["Espanha", "España"],
    cities: [
      ["Madrid", "Madri"],
      "Barcelona",
      ["Valencia", "Valência"],
      ["Seville", "Sevilha", "Sevilla"],
      ["Bilbao", "Bilbau"],
      ["Málaga", "Malaga"],
      "Zaragoza",
      ["Palma de Mallorca", "Palma de Maiorca"],
      "Alicante",
      "Granada",
      "Las Palmas",
      "Santa Cruz de Tenerife",
    ],
  },
  {
    name: "Netherlands",
    aliases: ["Holanda", "Holland", "Nederland"],
    cities: [
      ["Amsterdam", "Amsterdã"],
      ["Rotterdam", "Roterdã"],
      ["The Hague", "Haia", "Den Haag"],
      "Utrecht",
      "Eindhoven",
      "Groningen",
      "Delft",
      "Leiden",
      "Haarlem",
      ["Nijmegen", "Nimega"],
    ],
  },
  {
    name: "United Kingdom",
    aliases: ["Reino Unido", "UK", "Great Britain"],
    cities: [
      ["London", "Londres"],
      "Manchester",
      ["Edinburgh", "Edimburgo"],
      "Bristol",
      "Cambridge",
      "Oxford",
      "Birmingham",
      "Leeds",
      "Glasgow",
      "Brighton",
      "Liverpool",
      "Belfast",
      "Cardiff",
      "Sheffield",
      "Newcastle",
      "Reading",
    ],
  },
  {
    name: "Ireland",
    aliases: ["Irlanda"],
    cities: ["Dublin", "Cork", "Galway", "Limerick"],
  },
  {
    name: "France",
    aliases: ["França"],
    cities: [
      "Paris",
      "Lyon",
      ["Marseille", "Marselha"],
      "Toulouse",
      ["Bordeaux", "Bordéus"],
      "Nice",
      "Nantes",
      "Lille",
      ["Strasbourg", "Estrasburgo"],
      "Montpellier",
      "Rennes",
      "Grenoble",
      "Sophia Antipolis",
    ],
  },
  {
    name: "Italy",
    aliases: ["Itália", "Italia"],
    cities: [
      ["Milan", "Milão", "Milano"],
      ["Rome", "Roma"],
      ["Turin", "Turim", "Torino"],
      ["Bologna", "Bolonha"],
      ["Florence", "Florença", "Firenze"],
      ["Naples", "Nápoles", "Napoli"],
      ["Venice", "Veneza", "Venezia"],
      ["Padua", "Pádua", "Padova"],
      "Trento",
      "Pisa",
      ["Genoa", "Génova", "Genova"],
      "Verona",
    ],
  },
  {
    name: "Switzerland",
    aliases: ["Suíça", "Schweiz", "Suisse"],
    cities: [
      ["Zurich", "Zurique", "Zürich"],
      ["Geneva", "Genebra", "Genève"],
      ["Basel", "Basileia"],
      ["Bern", "Berna"],
      "Lausanne",
      "Lugano",
      "Zug",
      "Winterthur",
    ],
  },
  {
    name: "Austria",
    aliases: ["Áustria", "Österreich"],
    cities: [["Vienna", "Viena", "Wien"], "Graz", "Linz", ["Salzburg", "Salzburgo"], "Innsbruck"],
  },
  {
    name: "Belgium",
    aliases: ["Bélgica", "België"],
    cities: [
      ["Brussels", "Bruxelas", "Bruxelles"],
      ["Antwerp", "Antuérpia", "Antwerpen"],
      ["Ghent", "Gante", "Gent"],
      ["Leuven", "Lovaina"],
      ["Bruges", "Brugge"],
      ["Liège", "Liege"],
    ],
  },
  {
    name: "Sweden",
    aliases: ["Suécia", "Sverige"],
    cities: [
      ["Stockholm", "Estocolmo"],
      ["Gothenburg", "Gotemburgo", "Göteborg"],
      ["Malmö", "Malmo"],
      "Uppsala",
      "Lund",
      ["Linköping", "Linkoping"],
    ],
  },
  {
    name: "Denmark",
    aliases: ["Dinamarca", "Danmark"],
    cities: [["Copenhagen", "Copenhague", "København"], "Aarhus", "Odense", "Aalborg"],
  },
  {
    name: "Norway",
    aliases: ["Noruega", "Norge"],
    cities: ["Oslo", "Bergen", "Trondheim", "Stavanger"],
  },
  {
    name: "Finland",
    aliases: ["Finlândia", "Suomi"],
    cities: [["Helsinki", "Helsinque"], "Espoo", "Tampere", "Turku", "Oulu"],
  },
  {
    name: "Poland",
    aliases: ["Polônia", "Polska"],
    cities: [
      ["Warsaw", "Varsóvia", "Warszawa"],
      ["Kraków", "Cracóvia", "Krakow"],
      ["Wrocław", "Wroclaw"],
      ["Poznań", "Poznan"],
      ["Gdańsk", "Gdansk"],
      ["Łódź", "Lodz"],
      "Katowice",
    ],
  },
  {
    name: "Czechia",
    aliases: ["República Tcheca", "Czech Republic"],
    cities: [["Prague", "Praga", "Praha"], "Brno", "Ostrava", ["Plzeň", "Plzen", "Pilsen"]],
  },
  { name: "Estonia", aliases: ["Estônia", "Eesti"], cities: ["Tallinn", "Tartu"] },
  { name: "Latvia", aliases: ["Letônia"], cities: [["Riga", "Rīga"]] },
  { name: "Lithuania", aliases: ["Lituânia"], cities: ["Vilnius", "Kaunas"] },
  {
    name: "Romania",
    aliases: ["Romênia", "România"],
    cities: [
      ["Bucharest", "Bucareste", "București"],
      "Cluj-Napoca",
      ["Timișoara", "Timisoara"],
      ["Iași", "Iasi"],
      ["Brașov", "Brasov"],
    ],
  },
  {
    name: "Hungary",
    aliases: ["Hungria", "Magyarország"],
    cities: [["Budapest", "Budapeste"], "Debrecen", "Szeged"],
  },
  {
    name: "Bulgaria",
    aliases: ["Bulgária"],
    cities: [["Sofia", "Sófia"], "Plovdiv", "Varna"],
  },
  {
    name: "Greece",
    aliases: ["Grécia"],
    cities: [["Athens", "Atenas"], ["Thessaloniki", "Tessalônica"], "Patras"],
  },
  { name: "Croatia", aliases: ["Croácia", "Hrvatska"], cities: ["Zagreb", "Split", "Rijeka"] },
  {
    name: "Serbia",
    aliases: ["Sérvia"],
    cities: [["Belgrade", "Belgrado", "Beograd"], "Novi Sad", ["Niš", "Nis"]],
  },
  {
    name: "Slovenia",
    aliases: ["Eslovênia"],
    cities: [["Ljubljana", "Liubliana"], "Maribor"],
  },
  {
    name: "Slovakia",
    aliases: ["Eslováquia"],
    cities: ["Bratislava", ["Košice", "Kosice"]],
  },
  { name: "Luxembourg", aliases: ["Luxemburgo"], cities: [["Luxembourg", "Luxemburgo"]] },
  { name: "Malta", cities: [["Valletta", "Valeta"], "Sliema"] },
  {
    name: "Ukraine",
    aliases: ["Ucrânia"],
    cities: [["Kyiv", "Kiev"], "Lviv", "Kharkiv", ["Odesa", "Odessa"]],
  },
  {
    name: "Türkiye",
    aliases: ["Turquia", "Turkey"],
    cities: [
      ["Istanbul", "Istambul"],
      ["Ankara", "Ancara"],
      ["Izmir", "İzmir"],
    ],
  },
  {
    name: "United States",
    aliases: ["Estados Unidos", "USA", "US"],
    cities: [
      ["San Francisco", "São Francisco"],
      ["New York", "Nova York"],
      "Seattle",
      "Austin",
      "Boston",
      "Los Angeles",
      "Chicago",
      "Denver",
      "Miami",
      "Atlanta",
      "Portland",
      "San Diego",
      "Washington",
      ["Philadelphia", "Filadélfia"],
      "Dallas",
      "Houston",
      "Phoenix",
      "Nashville",
      "Pittsburgh",
      "Minneapolis",
      "Raleigh",
      "Salt Lake City",
      "San Jose",
      "Palo Alto",
    ],
  },
  {
    name: "Canada",
    aliases: ["Canadá"],
    cities: [
      "Toronto",
      "Vancouver",
      ["Montreal", "Montréal"],
      "Ottawa",
      "Calgary",
      "Waterloo",
      ["Quebec City", "Quebec", "Québec"],
      "Edmonton",
      "Halifax",
      "Victoria",
    ],
  },
  {
    name: "Mexico",
    aliases: ["México"],
    cities: [
      ["Mexico City", "Cidade do México", "Ciudad de México"],
      "Guadalajara",
      "Monterrey",
      ["Querétaro", "Queretaro"],
      ["Mérida", "Merida"],
      "Puebla",
      "Tijuana",
    ],
  },
  {
    name: "Brazil",
    aliases: ["Brasil"],
    cities: [
      ["São Paulo", "Sao Paulo"],
      ["Rio de Janeiro", "Rio"],
      "Belo Horizonte",
      "Curitiba",
      "Porto Alegre",
      ["Florianópolis", "Florianopolis"],
      ["Brasília", "Brasilia"],
      "Recife",
      "Fortaleza",
      "Salvador",
      "Campinas",
      ["Goiânia", "Goiania"],
      "Manaus",
      ["Belém", "Belem"],
      ["Vitória", "Vitoria"],
      "Natal",
      ["João Pessoa", "Joao Pessoa"],
      ["Maceió", "Maceio"],
      ["São José dos Campos", "Sao Jose dos Campos"],
      "Joinville",
      "Londrina",
      ["Ribeirão Preto", "Ribeirao Preto"],
      ["Uberlândia", "Uberlandia"],
      "Santos",
      "Sorocaba",
      "Blumenau",
      "Caxias do Sul",
      ["Niterói", "Niteroi"],
      "Campo Grande",
      ["Cuiabá", "Cuiaba"],
      ["Teresina", "Terezina"],
      ["São Luís", "Sao Luis"],
      "Aracaju",
      "Palmas",
      "Juiz de Fora",
    ],
  },
  {
    name: "Argentina",
    cities: ["Buenos Aires", ["Córdoba", "Cordoba"], ["Rosario", "Rosário"], "Mendoza", "La Plata"],
  },
  {
    name: "Chile",
    cities: [
      "Santiago",
      ["Valparaíso", "Valparaiso"],
      ["Concepción", "Concepcion"],
      "Viña del Mar",
    ],
  },
  {
    name: "Colombia",
    aliases: ["Colômbia"],
    cities: [["Bogotá", "Bogota"], ["Medellín", "Medellin"], "Cali", "Barranquilla", "Cartagena"],
  },
  {
    name: "Uruguay",
    aliases: ["Uruguai"],
    cities: [["Montevideo", "Montevidéu"], "Punta del Este"],
  },
  { name: "Peru", cities: ["Lima", "Arequipa"] },
  { name: "Costa Rica", cities: [["San José", "San Jose"]] },
  { name: "Panama", aliases: ["Panamá"], cities: [["Panama City", "Cidade do Panamá"]] },
  {
    name: "Australia",
    aliases: ["Austrália"],
    cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", ["Canberra", "Camberra"]],
  },
  {
    name: "New Zealand",
    aliases: ["Nova Zelândia"],
    cities: ["Auckland", "Wellington", "Christchurch"],
  },
  {
    name: "Japan",
    aliases: ["Japão"],
    cities: [["Tokyo", "Tóquio"], "Osaka", ["Kyoto", "Quioto"], "Yokohama", "Fukuoka", "Nagoya"],
  },
  {
    name: "South Korea",
    aliases: ["Coreia do Sul", "Korea"],
    cities: [["Seoul", "Seul"], "Busan", "Incheon"],
  },
  { name: "Singapore", aliases: ["Singapura"], cities: [["Singapore", "Singapura"]] },
  {
    name: "China",
    cities: [
      ["Shanghai", "Xangai"],
      ["Beijing", "Pequim"],
      "Shenzhen",
      "Hangzhou",
      "Guangzhou",
      "Hong Kong",
    ],
  },
  {
    name: "India",
    aliases: ["Índia"],
    cities: [
      ["Bangalore", "Bengaluru"],
      "Hyderabad",
      "Mumbai",
      "Pune",
      ["Delhi", "Deli", "New Delhi"],
      "Chennai",
      ["Gurgaon", "Gurugram"],
      "Noida",
    ],
  },
  { name: "Indonesia", aliases: ["Indonésia"], cities: [["Jakarta", "Jacarta"], "Bali"] },
  {
    name: "Thailand",
    aliases: ["Tailândia"],
    cities: [["Bangkok", "Banguecoque"], "Chiang Mai"],
  },
  {
    name: "Vietnam",
    aliases: ["Vietnã"],
    cities: [["Ho Chi Minh City", "Ho Chi Minh", "Saigon"], ["Hanoi", "Hanói"], "Da Nang"],
  },
  { name: "Philippines", aliases: ["Filipinas"], cities: ["Manila", "Cebu"] },
  { name: "Malaysia", aliases: ["Malásia"], cities: ["Kuala Lumpur"] },
  {
    name: "United Arab Emirates",
    aliases: ["Emirados Árabes Unidos", "UAE"],
    cities: ["Dubai", "Abu Dhabi"],
  },
  {
    name: "Israel",
    cities: ["Tel Aviv", ["Jerusalem", "Jerusalém"], "Haifa"],
  },
  {
    name: "Saudi Arabia",
    aliases: ["Arábia Saudita"],
    cities: [
      ["Riyadh", "Riade"],
      ["Jeddah", "Jidá"],
    ],
  },
  { name: "Egypt", aliases: ["Egito"], cities: ["Cairo", "Alexandria"] },
  {
    name: "South Africa",
    aliases: ["África do Sul"],
    cities: [
      ["Cape Town", "Cidade do Cabo"],
      ["Johannesburg", "Joanesburgo"],
      "Durban",
      ["Pretoria", "Pretória"],
    ],
  },
  { name: "Kenya", aliases: ["Quênia"], cities: [["Nairobi", "Nairóbi"]] },
  { name: "Nigeria", aliases: ["Nigéria"], cities: ["Lagos", "Abuja"] },
  { name: "Morocco", aliases: ["Marrocos"], cities: ["Casablanca", "Rabat"] },
  {
    name: "Remote",
    aliases: ["Remoto"],
    cities: [
      ["Remote — Global", "Remoto Global"],
      ["Remote — Europe", "Remoto Europa"],
      ["Remote — European Union", "Remoto União Europeia", "Remote EU"],
      ["Remote — Americas", "Remoto Américas"],
      ["Remote — Brazil", "Remoto Brasil"],
    ],
  },
];
